package com.shuttl.android.analyticswrapper.clevertap

object ClevertapConstants {
    const val CT_IDENTITY = "Identity"
    const val CT_ENCRYPTED_USER_ID = "Encrypted_User_Id"
    const val CT_EMAIL = "Email"
    const val CT_NAME = "NAME"
    const val CT_PHONE = "Phone"
    const val CT_MOBILE_NUMBER = "Mobile_Number"
    const val CT_USER_GENDER = "USER_GENDER"
    const val CT_GENDER = "Gender"
    const val CT_REFERRAL_CONTACT = "REFERRER_NUMBER"
    const val CT_HOME_LOCATION = "HOME_ADDRESS"
    const val CT_HOME_LATITUDE = "HOME_LATITUDE"
    const val CT_HOME_LONGITUDE = "HOME_LONGITUDE"
    const val CT_HOME_LOCATION_CITY = "HOME_CITY"
    const val CT_OFFICE_LOCATION = "WORK_ADDRESS"
    const val CT_OFFICE_LATITUDE = "WORK_LATITUDE"
    const val CT_OFFICE_LONGITUDE = "WORK_LONGITUDE"
    const val CT_OFFICE_LOCATION_CITY = "WORK_CITY"
    const val CT_DATE_OF_BIRTH = "BIRTH_DATE"
    const val CT_DOB = "DOB"
    const val CT_CORPORATE_EMAIL_ID = "CORPORATE_EMAIL_ID"
    const val CT_TIME_TO_LEAVE_HOME = "TIME_TO_LEAVE_HOME"
    const val CT_TIME_TO_LEAVE_WORK = "TIME_TO_LEAVE_WORK"
    const val CT_APPS_FLYER_DEVICE_ID = "APPS_FLYER_DEVICE_ID"
    const val CT_USER_SELECTED_CITY = "USER_SELECTED_CITY"
}